In [1]:
import pandas as pd
import numpy

#learning stuff
from sklearn import neighbors
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from math import sqrt

#graphing stuff!
%matplotlib notebook
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

Checkpoint \#1:
So far, we've refined our dataset in Excel (DataRefined.xlsx), pulled it into the notebook, and begun to lay that data out in an accessible fashion for use later. 
Basically, the Excel has several rows for musical metadata, which are pulled into a DataFrame called soundData, and two rows for mood data (created by our team) that are pulled into their own DataFrame emotionData. 
These are each being reduced to a single-column array, through PCA. These will be paired together to begin predicting emotionData. 

Unexpected Challenges:
- Randomizing Excel data - more complicated than it seems!
- Finding and eliminating NaNs in datasets.

Next Up (By Tuesday):
- Complete training set
- Begin training algorithms!

Note: I reduced the dataset to a nice round 10 thousand

In [2]:
data = pd.read_excel('DataRefined.xlsx')
#data is a pandas DataFrame
data_array = data.values
#data_array is a bit easier to think about - each value can be accessed with data_array[x]

In [3]:
#soundData is trimmed DataFrame that only contains song metadata
soundData = data.drop(columns=['artist_name', 'track_url', 'happysad', 'calmenergetic', 'trainortest', 'random', 'PCA output?', 'track_id'])
soundData.fillna(0)

acousticness  danceability    energy  instrumentalness  liveness  \
0         0.078285      0.314572  0.309468          0.089045  0.354460   
1         0.907184      0.608202  0.487272          0.952051  0.147523   
2         0.902820      0.417216  0.192552          0.941335  0.103392   
3         0.514903      0.297365  0.716660          0.884307  0.164822   
4         0.420525      0.419414  0.800006          0.917086  0.188013   
5         0.416963      0.756106  0.286637          0.000584  0.069551   
6         0.694238      0.408591  0.919719          0.876129  0.131418   
7         0.048519      0.667429  0.769637          0.852260  0.244618   
8         0.945563      0.646874  0.295514          0.222247  0.060897   
9         0.897702      0.796883  0.274274          0.939014  0.102938   
10        0.985751      0.457520  0.022572          0.218727  0.122267   
11        0.354901      0.508020  0.407293          0.893925  0.118368   
12        0.988454      0.713819  0.031309          0.938388  0.114263   
13        0.001689      0.198057  0.991397          0.729470  0.653096   
14        0.976350      0.603455  0.321455          0.888967  0.108793   
15        0.980851      0.620562  0.117482          0.866976  0.068220   
16        0.838158      0.331324  0.744305          0.883808  0.097817   
17        0.761327      0.277263  0.705548          0.744409  0.205326   
18        0.521260      0.867076  0.293070          0.818247  0.122813   
19        0.747710      0.607210  0.361172          0.933361  0.102026   
20        0.535981      0.442008  0.734827          0.961365  0.453037   
21        0.500190      0.381392  0.009124          0.077192  0.113638   
22        0.232200      0.462682  0.566474          0.671058  0.084181   
23        0.096757      0.212331  0.921885          0.950515  0.072194   
24        0.939971      0.272441  0.190383          0.964539  0.084715   
25        0.388360      0.814581  0.802764          0.000017  0.174730   
26        0.972420      0.721255  0.069825          0.041613  0.109960   
27        0.556361      0.069153  0.172375          0.761042  0.210642   
28        0.995796      0.402116  0.002939          0.882777  0.116060   
29        0.791559      0.567913  0.697096          0.941815  0.131790   
...            ...           ...       ...               ...       ...   
9970      0.016262      0.343433  0.544576          0.832607  0.099290   
9971      0.995604      0.187577  0.283821          0.896029  0.120486   
9972      0.785634      0.756846  0.551810          0.045698  0.120505   
9973      0.995644      0.342928  0.109225          0.972812  0.185246   
9974      0.514009      0.554340  0.079318          0.913141  0.106724   
9975      0.115343      0.524946  0.167544          0.889032  0.387350   
9976      0.064281      0.526225  0.873696          0.000091  0.176412   
9977      0.087853      0.328178  0.874371          0.784072  0.353762   
9978      0.992985      0.290151  0.747619          0.972315  0.111608   
9979      0.917401      0.402591  0.264057          0.070472  0.096537   
9980      0.995796      0.455862  0.212012          0.918122  0.455044   
9981      0.995796      0.388273  0.183784          0.000015  0.144584   
9982      0.686675      0.429400  0.321300          0.865545  0.104000   
9983      0.986102      0.442724  0.461540          0.921036  0.248762   
9984      0.921488      0.719879  0.269671          0.021384  0.110928   
9985      0.870657      0.572340  0.312209          0.976504  0.104480   
9986      0.995438      0.448615  0.103161          0.962223  0.734475   
9987      0.995650      0.195831  0.044155          0.000016  0.084981   
9988      0.929728      0.257104  0.006165          0.712866  0.102265   
9989      0.934078      0.325790  0.881880          0.932064  0.097758   
9990      0.829937      0.547937  0.656592          0.340704  0.074949   
9991      0.254056      0.840943  0.946897          0.696025  0.071731   
9992      

In [4]:
#print(data.head())

In [5]:
emotionData = data.drop(columns=['artist_name', 'track_url', 'acousticness', 'danceability', 'energy', 'instrumentalness', 'liveness', 'speechiness', 'tempo', 'valence', 'trainortest', 'random', 'PCA output?', 'track_id'])
emotionData.fillna(0)

happysad  calmenergetic
0          5.0            8.0
1          1.0            2.0
2          0.0            0.0
3          0.0            0.0
4          7.0            3.0
5          3.0            4.0
6          4.0            6.0
7          0.0            0.0
8          8.0            6.0
9          4.0            1.0
10         3.0            1.0
11         3.0            7.0
12         8.0            9.0
13         0.0            0.0
14         7.0            8.0
15         6.0            6.0
16         6.0            8.0
17         3.0            2.0
18         3.0            6.0
19         1.0            3.0
20         4.0            8.0
21         8.0            5.0
22         0.0            0.0
23         0.0            0.0
24         6.0            9.0
25         4.0            6.0
26         5.0            8.0
27         0.0            0.0
28         6.0            7.0
29         4.0            4.0
...        ...            ...
9970       0.0            0.0
9971       0.0            0.0
9972       0.0            0.0
9973       0.0            0.0
9974       0.0            0.0
9975       0.0            0.0
9976       0.0            0.0
9977       0.0            0.0
9978       0.0            0.0
9979       0.0            0.0
9980       0.0            0.0
9981       0.0            0.0
9982       0.0            0.0
9983       0.0            0.0
9984       0.0            0.0
9985       0.0            0.0
9986       0.0            0.0
9987       0.0            0.0
9988       0.0            0.0
9989       0.0            0.0
9990       0.0            0.0
9991       0.0            0.0
9992       0.0            0.0
9993       0.0            0.0
9994       0.0            0.0
9995       0.0            0.0
9996       0.0            0.0
9997       0.0            0.0
9998       0.0            0.0
9999       0.0            0.0

[10000 rows x 2 columns]

In [6]:
#print(data_array[0])

In [7]:
#data.shape

In [8]:
#data_array[:5]

Goal here: PCA 

In [9]:
pca = PCA(n_components = 1)
numpy.nan_to_num(soundData)
numpy.isfinite(soundData).all()

#these columsn occasionally have empty values so here we just set them to 0
for index, row in soundData.iterrows():
    if(not numpy.isfinite(row["danceability"])):
       row["danceability"] = 0 
    if(not numpy.isfinite(row["speechiness"])):
       row["speechiness"] = 0 
    if(not numpy.isfinite(row["valence"])):
       row["valence"] = 0 
eigenbasis = pca.fit(soundData)

In [10]:
soundDataPCA = eigenbasis.transform(soundData)

In [11]:
soundDataPCA.shape

(10000, 1)

In [12]:
soundDataPCA[:10]

array([[  4.97565375],
       [  5.06488366],
       [-12.23413748],
       [ 35.01374082],
       [-24.09670909],
       [-23.89830834],
       [-13.23870497],
       [ 17.21177759],
       [ 10.24802095],
       [  3.13282303]])

In [13]:
for index, row in emotionData.iterrows():
    if(not numpy.isfinite(row["happysad"])):
       row["happysad"] = 0 
    if(not numpy.isfinite(row["calmenergetic"])):
       row["calmenergetic"] = 0 

In [39]:
emotionPCA = PCA(n_components = 1)
eigenbasisEmotion = emotionPCA.fit(emotionData)
emotionDataPCA = eigenbasisEmotion.transform(emotionData)
emotionDataPCA.shape

(10000, 1)

In [40]:
emotionDataPCA[:10]

array([[ 9.29015179],
       [ 2.11661289],
       [-0.06235761],
       [-0.06235761],
       [ 6.70754873],
       [ 4.93221078],
       [ 7.11118128],
       [-0.06235761],
       [ 9.6576908 ],
       [ 3.25532346]])

In [41]:
trainData_emotion = emotionDataPCA[:100]
trainData_emotion[:10]

array([[ 9.29015179],
       [ 2.11661289],
       [-0.06235761],
       [-0.06235761],
       [ 6.70754873],
       [ 4.93221078],
       [ 7.11118128],
       [-0.06235761],
       [ 9.6576908 ],
       [ 3.25532346]])

In [44]:
twotrainData_emotion = []
for i in range(100):
    #print(emotionDataPCA[i])
    twotrainData_emotion.append(emotionDataPCA[i][0])
twotrainData_emotion[:10]

[9.290151789482138,
 2.116612892179925,
 -0.06235761408559831,
 -0.06235761408559831,
 6.707548727093725,
 4.9322107769510914,
 7.111181283216615,
 -0.06235761408559831,
 9.657690797239189,
 3.255323463816915]

In [30]:
for i in range(len(trainData_emotion)):
    #print(trainData_emotion[i][0])
    hold = trainData_emotion[i][0]
    trainData_emotion[i] = 0
    print(hold)
    #trainData_emotion[i] = trainData_emotion[i][0]
trainData_emotion[:10]


9.290151789482145
2.116612892179927
-0.06235761408559832
-0.06235761408559832
6.707548727093709
4.932210776951093
7.111181283216618
-0.06235761408559832
9.657690797239178
3.2553234638169033
2.6186960853112637
7.245725468590922
11.971205488879006
-0.06235761408559832
10.563406546493423
8.384436040227898
9.926779167987783
3.3898676491912068
6.474553904710979
2.88778445605987
8.653524410976505
8.886519233359236
-0.06235761408559832
-0.06235761408559832
10.697950731867726
7.111181283216618
9.290151789482145
-0.06235761408559832
9.155607604107841
5.568838155456732
7.478720290973652
5.066754962325397
4.663122406202486
8.92261278172511
2.88778445605987
3.6589560199398132
4.295583398445453
5.201299147699699
4.295583398445453
6.609098090085283
5.066754962325397
9.021063418733538
6.340009719336676
1.2108971429256814
9.021063418733538
9.290151789482145
6.474553904710979
8.788068596350808
8.518980225602201
7.245725468590922
4.295583398445453
7.245725468590922
9.155607604107841
8.384436040227898
-0

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [19]:
trainData_sound = soundDataPCA[:100]
trainData_sound[:10]

array([[  4.97565375],
       [  5.06488366],
       [-12.23413748],
       [ 35.01374082],
       [-24.09670909],
       [-23.89830834],
       [-13.23870497],
       [ 17.21177759],
       [ 10.24802095],
       [  3.13282303]])

In [20]:
testData_emotion = emotionDataPCA[100:]
testData_emotion[:10]

array([[-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761],
       [-0.06235761]])

In [21]:
testData_sound = soundDataPCA[100:]
testData_sound[:10]

array([[ 22.63481199],
       [ 11.05482994],
       [-39.84525749],
       [-58.10276798],
       [ -1.63721607],
       [ 30.4292374 ],
       [  1.55383814],
       [ 33.06567168],
       [ 32.70214667],
       [-26.81139913]])

In [22]:
type(trainData_sound[0][0])

numpy.float64

In [23]:
classifier = neighbors.KNeighborsClassifier(metric='euclidean', n_neighbors=10)
classifier.fit(trainData_emotion, trainData_sound)
#classifier.score(testData_emotion, testData_sound)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


ValueError: Unknown label type: 'continuous'